### ISSUE TITLE
Can this model be used for 5DOF robot? (it's actually 6dof but +1 is for gripper closing/opeing)

### ISSUE THREAD

**Issue by datonefaridze** [google-deepmind/open_x_embodiment#20]
If it can't be used the how can i fine tune it? i mean we can fine tune models trained on imagenet, is it possible to do it here?

**Comment by psanketi** [comment]
Currently the model will be most suited for 7 DOF arms. As a baseline, you could try just ignoring the appropriate degrees and using the rest. I think the right way might be to further fine-tune that model on your data (and converting the 7 degrees to 5 that make the most sense for your arm.)
Yes, you should be able to fine tune the model on your own. The Colabs show how to load the model and run inference on it. You can try to work off of that in the framwork of your choice. We are hoping to release Jax model plus finetuning reference code soon, so that should help a lot!

**Comment by datonefaridze** [comment]
@psanketi hello,can you give me approximate date when the code in jax will be released? (2 weeks, 3, 4?)

**Comment by datonefaridze** [comment]
@psanketi asking because i didn't manage to fine tune the model, and i might go with another solution (this one will require for me to spend at least a month to finish). so that's why i was interested in time period, if deepmind plans to publish code in 2 weeks i wouldn't go for another solution
