### ISSUE TITLE
How can I get ALOHA data without Registered Dataset Name?

### ISSUE THREAD

**Issue by alexfrom0815** [google-deepmind/open_x_embodiment#49]
It seems that the document "Open X-Embodiment Dataset Overview" contains the ALOHA dataset, but no Registered Dataset Name is provided. How can we download the ALOHA dataset processed in the unified format adopted by Open X-Embodiment?

**Comment by kpertsch** [comment]
Thanks for reaching out! I believe there was an issue where the ALOHA RLDS dataset was corrupted, so it's not uploaded to the google bucket -- I have since re-converted the dataset and we're in the process of uploading it -- it will probably take a week or two before it's up -- in the meantime happy to give you access if you want to send me your email to karl.pertsch@gmail.com

**Comment by jimmieliu** [comment]
Has ALOHA RLDS dataset been uploaded yet?
